# base image
FROM python:3.10-slim

# enviironment variables
ENV APP_HOME=/app
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=$APP_HOME

# create app directory
WORKDIR $APP_HOME

# install dependancies
RUN apt-get update && \
    apt-get install -y gettext && \
    apt install -y ncat && \
    python -m pip install --upgrade pip && \
    apt install postgresql postgresql-contrib -y && \
    pip3 install poetry

# copy files
COPY . $APP_HOME

# install dependancies
RUN poetry config virtualenvs.create false
RUN poetry install


# changing mode of entrypoint
RUN chmod +x ./docker-entrypoint.dev.sh

EXPOSE 5000
# run script 
ENTRYPOINT ["./docker-entrypoint.dev.sh"]
